export type InputAction =
  | "move_up"
  | "move_down"
  | "move_left"
  | "move_right"
  | "confirm"
  | "cancel"
  | "pause"
  | "card_1"
  | "card_2"
  | "card_3"
  | "card_4"
  | "card_5"
  | "end_turn"
  | "toggle_debug";
